template = ""
rev_id = 260
template_sha = "2e95e152f66f76c7c7a22b2f9d91adbb75b07d95"

[replacements]
__GLOTTOLOG_ID__ = "anam1249"
__LICENSE__ = "GPLv3"
__REPO__ = "lang-aan"
__UND2C__ = "aan"
__UNDEFINED__ = "Anamb√©"
__UND__ = "aan"
