template = ""
rev_id = 266
template_sha = "0bf1857d37e3d9d859c2f97c9772ed27d291955c"

[replacements]
__GLOTTOLOG_ID__ = "anam1249"
__LICENSE__ = "GPLv3"
__REPO__ = "lang-aan"
__UND2C__ = "aan"
__UNDEFINED__ = "Anamb√©"
__UND__ = "aan"
